---
- debug: msg={{ os_dist}}
- debug: msg={{ os_version }}

- name: "copy hosts"
  template: src=hosts.j2 dest=/etc/hosts

- name: "{{ nic1 }}"
  nmcli: conn_name={{ nic1 }} ip4={{ bastion_node01_nic1_ip4 }}/24 dns4={{ bastion_node01_nic1_dns4 }} dns4_ignore_auto=yes state=present method4=manual autoconnect=true
- shell: nmcli c mod {{ nic1 }} ipv4.dns-priority 10

- name: "{{ nic2 }}"
  nmcli: conn_name={{ nic2 }} ip4={{ bastion_node01_nic2_ip4 }}/24 dns4={{ bastion_node01_nic2_dns4 }} dns4_ignore_auto=yes state=present method4=manual autoconnect=true
- shell: nmcli c mod {{ nic2 }} ipv4.dns-priority 30

- name: "{{ nic3 }}"
  nmcli: conn_name={{ nic3 }} ip4={{ bastion_node01_nic3_ip4 }}/24 dns4={{ bastion_node01_nic3_dns4 }} dns4_ignore_auto=yes state=present method4=manual autoconnect=true gw4=192.168.11.1
- shell: nmcli c mod {{ nic3 }} ipv4.dns-priority 30

- openssh_keypair: path=/root/.ssh/id_ed25519 force=false type=ed25519
